name = "short-drama-viewing-history"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# 静态资源配置
[assets]
directory = "./public"
not_found_handling = "single-page-application"

# Hyperdrive 数据库配置（SQLPub）
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "15f4b03f63964fbc9089cba4e140beba"
